name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
     uses: ./.github/workflows/called.yaml
     with:
      branch: "stage_5.15.4"
      centos_ver: "8"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.full_rpm_path }}
