name: Close missing info issues

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  close-missing-info-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Close missing info issues
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          GET_ISSUES_CMD="gh issue list --label 'missing info' --state open --json number,labels,createdAt"
          FILTER_ISSUES_CMD="jq -r '.[] | select(((now - (.createdAt | fromdateiso8601)) / 86400) > 7) | .number'"
          CLOSE_ISSUE_CMD="gh issue close"
          
          issues=$(eval "$GET_ISSUES_CMD")
          echo $issues
          
          # Filter issues older than 7 days
          issue_numbers=$(echo "$issues" | eval "$FILTER_ISSUES_CMD")
          echo $issue_numbers
                    
          # Loop through each issue number and close it with a comment
          closure_comment='This issue is being closed because it has been labeled \"missing info\" for more than a week. Please provide the requested information and reopen the issue if necessary.'
          for issue_number in $issue_numbers; do
            eval "$CLOSE_ISSUE_CMD $issue_number --comment $closure_comment"
          done
