name: Close issues labeled 'missing info' more than 5 minutes ago

on:
  schedule:
    - cron: '0 23 * * *'  # Runs every night 
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  close-labeled-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Close stale issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GET_ISSUES_CMD="gh issue list --label 'missing info' --state open --json number,title"
          CLOSE_ISSUE_CMD="gh issue close"
          COMMENT_CMD="gh issue comment"
          
          # Get list of issues with the 'missing_info' label
          issues=$(eval "$GET_ISSUES_CMD")
          echo $issues
          # Process each issue to check the label addition time
          echo "$issues" | jq -c '.[]' | while read issue; do
            issue_number=$(echo "$issue" | jq -r '.number')
            issue_title=$(echo "$issue" | jq -r '.title')

            # Get the timeline events for each issue
            events=$(gh api repos/${{ github.repository }}/issues/$issue_number/timeline --paginate --jq '[.[] | select(.event=="labeled" and .label.name=="missing info") | {created_at: .created_at}]')
            echo $issue_number
            echo $issue_title
            echo $events
            # Check if the label was added more than 5 minutes ago
            now=$(date -u +"%Y-%m-%dT%H:%M:00Z")
            five_minutes_ago=$(date -u -d "$now - 5 minutes" +"%Y-%m-%dT%H:%M:00Z")
            one_minutes_ago=$(date -u -d "$now - 1 minutes" +"%Y-%m-%dT%H:%M:00Z")
            # seven_days_ago=$(date -u -d "$now - 7 days" +"%Y-%m-%dT%H:%M:00Z")
            # three_days_ago=$(date -u -d "$now - 3 days" +"%Y-%m-%dT%H:%M:00Z")
            label_added_at=$(echo "$events" | jq -r '.[-1].created_at')
            
            echo $label_added_at
            echo $five_minutes_ago
            echo $one_minutes_ago
            
            if [[ "$label_added_at" > "$one_minutes_ago" && "$label_added_at" < "$five_minutes_ago" ]]; then
              echo "Commenting on issue #$issue_number: $issue_title"
              eval "$COMMENT_CMD $issue_number --body 'This issue has been labeled \"missing info\" for more than 3 days. Please provide the requested information.'"
            elif [[ "$label_added_at" > "$five_minutes_ago" ]]; then
              echo "Closing issue #$issue_number: $issue_title"
              eval "$CLOSE_ISSUE_CMD $issue_number --comment 'This issue is being closed because it was labeled \"missing info\" more than 5 minutes ago. Please provide the requested information and reopen the issue if necessary.'"
            fi
          done
