name: Missing Info issues

on:
  schedule:
    - cron: '0 23 * * *'    # Runs every night at 11PM
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  close-labeled-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Warn/Close Missing Info issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          days_to_warn_missing_info=3
          days_to_close_missing_info=7

          missing_info_warning='This issue has been labeled \"Missing Info\" for more than $days_to_warn_missing_info days. Please provide the requested information.'
          missing_info_closure_comment='This issue is being closed because it was labeled \"Missing Info\" more than $days_to_close_missing_info days ago. Please provide the requested information and reopen the issue if necessary.'

          missing_info_issues=$(gh issue list --label 'missing info' --state open --json number,title)
          echo "missing_info_issues=$missing_info_issues"

          # process each issue to check the label addition time
          echo "$missing_info_issues" | jq -c '.[]' | while read issue; do
            issue_number=$(echo "$issue" | jq -r '.number')
            issue_title=$(echo "$issue" | jq -r '.title')

            # 1. get the events for each issue, filter by Missing Info label
            # 2. find creation time of the last Missing Info label event
            events=$(gh api repos/${{ github.repository }}/issues/$issue_number/timeline --paginate --jq '[.[] | select(.event=="labeled" and .label.name=="missing info") | {created_at: .created_at}]')
            echo "issue_number=$issue_number, issue_title=$issue_title, events=$events"
            label_added_at=$(echo $events | jq -r '.[-1].created_at')
            echo "label_added_at=$label_added_at"

            # 3. find days diff between now and last Missing Info label added timestamp
            now=$(date -u +%s)
            echo "now=$now"
            label_added_timestamp=$(date -u -d "$label_added_at" +%s)
            echo "label_added_timestamp=$label_added_timestamp"
            time_diff_in_seconds=$((now - label_added_timestamp)) 
            echo "time_diff_in_seconds=$time_diff_in_seconds"
            time_diff_in_days=$(($time_diff_in_seconds/(24 * 60 * 60)))
            echo "time_diff_in_days=$time_diff_in_days"
            time_diff_in_mins=$(($time_diff_in_seconds/(60)))
            echo "time_diff_in_mins=$time_diff_in_mins"
            echo "now=$now label_added_timestamp=$label_added_timestamp time_diff_in_seconds=$time_diff_in_seconds time_diff_in_days=$time_diff_in_days time_diff_in_mins=$time_diff_in_mins"
            echo "days_to_warn_missing_info=$days_to_warn_missing_info"
            echo "days_to_close_missing_info=$days_to_close_missing_info"

            # 4. warn or close the issue upon reaching warning/closure thresholds
            if [ $time_diff_in_mins -eq $days_to_warn_missing_info ]; then
              echo "Commenting on issue #$issue_number: $issue_title"
              gh issue comment $issue_number --body "$missing_info_warning"
            elif [ $time_diff_in_mins -ge $days_to_close_missing_info ]; then
              echo "Closing issue #$issue_number: $issue_title"
              gh issue close $issue_number --comment "$missing_info_closure_comment"
            fi
          done
