name: Manual RPM Build Dispatch RHEL
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to RPM Build From'
        required: true
      tag:
        description: 'Additional tag for the build (such as alpha, beta, etc.) - Optional'
        default: ''
      rhel_ver:
        type: choice
        description: 'RHEL Base image (options: 8/9) - Optional, default is 9'
        default: '9'
        options: 
          - '8'
          - '9'

jobs:
  manual-rpm-build-and-upload-artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: alphaprinz/noobaa-core
          ref: ${{ github.event.inputs.branch }}

      - name: Prepare Suffix
        id: suffix
        if: ${{ github.event.inputs.tag != '' }}
        run: echo suffix="-${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
      
      - name: Prepare RHEL base image version
        id: rhel_ver
        run: echo "rhel_ver=${{ github.event.inputs.rhel_ver }}" >> $GITHUB_OUTPUT
      
      - name: Build RPM
        id: build_rpm
        run: |
          echo "Starting make rpm"
          make rpm CENTOS_VER=${{ steps.rhel_ver.outputs.rhel_ver }}
          echo "Make rpm completed"

      - name: Finalize RPM
        id: finalize_full_rpm_path
        run: |
          DATE=$(date +'%Y%m%d')
          VERSION=$(jq -r '.version' < ./package.json)
          RHEL_VER=${{ steps.rhel_ver.outputs.rhel_ver }}
          RPM_SUFFIX=el${RHEL_VER}.x86_64.rpm
          RPM_BASE_VERSION=noobaa-core-${VERSION}-${DATE}
          RPM_FULL_PATH=${RPM_BASE_VERSION}-${{ github.event.inputs.branch }}${{ steps.suffix.outputs.suffix }}.${RPM_SUFFIX}
          echo "rpm_full_path=${RPM_FULL_PATH}"
          cp ./build/rpm/${RPM_BASE_VERSION}.${RPM_SUFFIX} ${RPM_FULL_PATH}
          echo "rpm_full_path=${RPM_FULL_PATH}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: noobaa_rpm
          path: ${{ steps.finalize_full_rpm_path.outputs.rpm_full_path }}
