name: Non Containerized Unit Tests
on: 
  workflow_dispatch:

jobs:
  manual-nc-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: romayalon/noobaa-core     

      - name: Run nc tests
        id: run_nc_tests
        run: |
          echo "Starting to make nc tests"
          make run-nc-tests
          echo "Make run nc tests completed"
