name: Nightly RPM Build and Install Test
on: 
  schedule:
    - cron: '35 12 * * *'
      
jobs:
  call-master-rpm-build-and-install-9:
    uses: ./.github/workflows/rpm-build-and-install-test-base.yaml
    secrets: inherit
    with:
      branch: 'romy-rpm-build-and-install-test-and-action'
      centos_ver: '9'
  
  call-master-rpm-build-and-install-8:
    uses: ./.github/workflows/rpm-build-and-install-test-base.yaml
    secrets: inherit
    with:
      branch: 'romy-rpm-build-and-install-test-and-action'
      centos_ver: '8'
