name: Nightly RPM Build Dispatch
on: 
  schedule:
    - cron: "*/5 * * * *"

env: 
  UPLOAD_TO_S3: true

jobs:
  nightly-rpm-build-and-upload-artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Invoke RPM Build on Core Repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual RPM Build Dispatch
          inputs: '{ "branch": "romy-rpm-gaction", "tag": "" }' 
        env:
          UPLOAD_TO_S3: true
