name: RPM Build And Upload Flow
on: 
  workflow_call:
    inputs:
      branch: 
        type: string
        description: 'Run rpm build and upload to aws flow'
        default: 'master'

jobs:
  build-rpm-centos8:
    uses: ./.github/workflows/rpm-build-base.yaml
    with:
      branch: ${{ inputs.branch }}
      centos_ver: '8'

  upload-centos8-rpm-to-aws:
    needs: build-rpm-centos8
    uses: ./.github/workflows/upload-rpm-to-aws.yaml
    with:
      rpm_full_path: ${{ needs.build-rpm-centos8.outputs.rpm_full_path }}
    secrets: inherit

