name: RPM Build And Upload Flow
on: 
  workflow_call:
    inputs:
      branch: 
        type: string
        description: 'Run rpm build and upload to aws flow'
        default: 'master'

jobs:
  upload-centos8-rpm-to-aws:
    uses: ./.github/workflows/upload-rpm-to-aws.yaml
    with:
      rpm_full_path: 'ROMY_FULL_PATH8'
    secrets: inherit

  upload-centos9-rpm-to-aws:
    uses: ./.github/workflows/upload-rpm-to-aws.yaml
    with:
      rpm_full_path: 'ROMY_FULL_PATH9'
    secrets: inherit
